// obj architecture
/* 
{
    "code": 1000,
    "message": "SUCCESS",
    "payload": {...}
}
*/

export const member = {
  uri: 'members/member',
  desc: '유저 정보',
  data: {
    id: 63,
    code: 'M330000017',
    purpose: 'INVEST',
    authorities: ['ROLE_MEMBER'],
    investorTypeCode: 'I320',
    investorTypeName: 'CREDIT_FINANCIAL_INSTITUTION',
    loanerTypeCode: 'B300',
    loanerTypeName: 'CORPORATION_LOANER',
    email: 'hana@hanabank.co.kr',
    englishName: 'HANABANK',
    isPasswordChangeRequest: false,
    name: '하나은행',
    jobName: '',
    guid: 'LTEyMjMzOTE0NDA',
    sex: 'MQALE',
    type: 'CORPORATION',
    state: 'ACTIVE',
    amlState: 'AML_DONE',
    mainAddress: '서울 강서구 월정로18길 9 (화곡동)',
    subAddress: '3 층',
    sourceOfFund: '',
    specialIndustry: '',
    phone: '01064562278',
    contactPhone: '',
    encParam: null,
    amlId: null,
    pinId: null,
    socialCode1: '123456',
    socialCode2: '8121212',
    lastLoginAt: '2025-08-27 15:17:44',
    memo: null,
    isMailNotify: false,
    isSmsNotify: false,
    isKakaoNotify: false,
    telephone: '0212344321',
    businessCode: '1101122022',
    businessName: '이상욱',
    businessEnglishName: 'PARKJUNSEONG',
    corporateCode: '2222223******',
    ceoName: '박준성',
    ceoEnglishName: 'lee sy',
    ceoSocialCode1: '501212',
    ceoSocialCode2: '1234567',
    ownerName: '이승열',
    ownerEnglishName: 'lee sy',
    ownerSocialCode1: '501212',
    ownerSocialCode2: '501212',
    depositAccountTid: 'TTTTTT',
    depositAccountBank: 'NH농협은행',
    depositAccountCode: '011',
    depositAccountNumber: '79018940093715',
    depositAccountOwner: '하나은행',
    depositAccountCreatedAt: '2023-04-14 09:35:32',
    balance: 9891400,
    accountState: 'EXIST_SUCCESS',
    accountEnhancedState: 'NONE',
    kycState: 'SUCCESS',
    withdrawAccountBank: '국민은행',
    withdrawAccountCode: '004',
    withdrawAccountNumber: '778210218961',
    withdrawAccountOwner: '하나은행',
    withdrawAccountAddedAt: null,
    withdrawAccountExistAt: '2024-09-03 09:46:40',
    withdrawAccountValidAt: null,
    withdrawAccountValidIng: false,
    withdrawAccountValidLog: '',
    withdrawAccountEnhanceLog: '',
    kycLog: '',
    certLog: '',
    withdrawAccountValidTimeout: false,
    withdrawAccountEnhanceAt: null,
    repayAccountTid: null,
    repayAccountBank: null,
    repayAccountCode: null,
    repayAccountNumber: null,
    repayAccountOwner: null,
    repayAccountCreatedAt: null,
    certAt: null,
    isLoaning: false,
    isBelongCompany: false,
    loginFailCount: 0,
    createdAt: '2023-02-23 10:54:15',
    updatedAt: '2025-08-27 15:17:44',
    deletedAt: null,
    emailAuthCode: '',
    emailAuthCodeAt: null,
    emailAuthAt: null,
    cddAt: '2026-09-08 00:10:00',
    eddAt: null,
    riskScore: null,
    incomeScore: null,
    investorExpDate: null,
    ceoCorporateCode: null,
    ownerCorporateCode: null,
    leaveReason: null,
    isLeave: false,
    postCode: '07775',
    suggesterCode: null,
    suggesterName: null,
    managerCode: null,
    managerName: null,
    sourceOfFunds: null,
    sourceOfFundsEtc: null,
    purposeOfInvest: null,
    purposeOfInvestEtc: null,
    passwordDate: '2025-07-01 12:17:48',
    isDormant: false,
    meRecommenderCode: '3ABA',
    recommenderCode: null,
    nameOfAttorney: null,
    englishNameOfAttorney: null,
    socialCodeOfAttorney1: null,
    socialCodeOfAttorney2: null,
    memberCodeAmlAttornery: null,
    isMinor: false,
    level: 'NORMAL',
    mgLevelStartDate: null,
    mgLevelEndDate: null,
    mgmPoint: 0,
    multipleInvestRenewal: false,
  },
} as const;

export const mainData = {
  desc: '메인화면 배너',
  uri: 'main/banners/MAIN',
  data: {
    id: 53,
    type: 'MAIN',
    title: '하이펀딩, 온라인투자연계금융업 대출잔고 1위 달성',
    mobileTitle: null,
    titleColor: '#ffffffff',
    titlePcFontSize: 30,
    titleMoFontSize: 15,
    description: '',
    mobileDescription: null,
    descriptionColor: '#ffffffff',
    descPcFontSize: 20,
    descMoFontSize: 10,
    subDescription: '[관련 뉴스기사 보러가기]',
    mobileSubDescription: null,
    subDescriptionColor: '#ffffffff',
    subDescPcFontSize: 18,
    subDescMoFontSize: 12,
    file1:
      'https://kr.object.fin-ncloudstorage.com/lending/test/5a19a6d7-092b-4fea-a6e5-41a57f584e7c',
    file2:
      'https://kr.object.fin-ncloudstorage.com/lending/test/8d5e247f-5b9b-4ba5-a8a5-27247c4146b6',
    link: 'https://www.sedaily.com/NewsView/2GV6ZTH8XC',
    linkColor: '#ffffffff',
    state: 'ACTIVE',
    isNewTab: true,
    titleBold: true,
    descriptionBold: true,
    subDescriptionBold: true,
    titlePcTop: 160,
    titleMobileTop: 128,
    startAt: '2025-07-02 17:19:47',
    endAt: '2027-07-03 23:59:44',
    createdAt: '2025-07-02 16:59:11',
    updatedAt: '2025-07-03 09:08:09',
  },
} as const;

export const popup = {
  uri: 'main/banners/POPUP',
  desc: '메인화면 팝업',
  data: [
    {
      id: 52,
      type: 'POPUP',
      title: '단건투자이용알림',
      mobileTitle: null,
      titleColor: '#ffffffff',
      titlePcFontSize: 0,
      titleMoFontSize: 0,
      description: '',
      mobileDescription: null,
      descriptionColor: '#ffffffff',
      descPcFontSize: 0,
      descMoFontSize: 0,
      subDescription: '',
      mobileSubDescription: null,
      subDescriptionColor: '#ffffffff',
      subDescPcFontSize: 0,
      subDescMoFontSize: 0,
      file1:
        'https://kr.object.fin-ncloudstorage.com/lending/test/7d2ae456-8b6a-44df-86aa-f982f9de47c0',
      file2: null,
      link: 'https://hifunding.co.kr',
      linkColor: '#ffffffff',
      state: 'ACTIVE',
      isNewTab: false,
      titleBold: false,
      descriptionBold: false,
      subDescriptionBold: false,
      titlePcTop: 160,
      titleMobileTop: 128,
      startAt: '2025-04-15 13:22:02',
      endAt: '2025-12-24 13:22:16',
      createdAt: '2025-04-15 13:22:54',
      updatedAt: '2025-04-15 13:22:53',
    },
    {
      id: 42,
      type: 'POPUP',
      title: '1',
      mobileTitle: null,
      titleColor: '#ffffffff',
      titlePcFontSize: 0,
      titleMoFontSize: 0,
      description: '',
      mobileDescription: null,
      descriptionColor: '#ffffffff',
      descPcFontSize: 0,
      descMoFontSize: 0,
      subDescription: '',
      mobileSubDescription: null,
      subDescriptionColor: '#ffffffff',
      subDescPcFontSize: 0,
      subDescMoFontSize: 0,
      file1:
        'https://kr.object.fin-ncloudstorage.com/lending/test/bcb92d6e-6bd8-4cd8-97df-d1afa6333242',
      file2: null,
      link: 'http://dev-admin.hifunding.co.kr/',
      linkColor: '#ffffffff',
      state: 'ACTIVE',
      isNewTab: false,
      titleBold: false,
      descriptionBold: false,
      subDescriptionBold: false,
      titlePcTop: 160,
      titleMobileTop: 128,
      startAt: '2024-12-19 16:27:20',
      endAt: '2026-01-02 14:31:00',
      createdAt: '2024-12-19 16:26:30',
      updatedAt: '2025-04-15 14:02:19',
    },
  ],
} as const;

export const homeStatics = {
  uri: 'main/homeStatics',
  desc: '공시현황',
  data: {
    date: '2025-08-27',
    investmentsAvgRate: 12.07,
    accumulateInvestmentAmount: 1960920000,
    investmentBalance: 523016484,
    overdueRate: 49.03,
    principalLossRate: 0.0,
  },
};

export const products = {
  uri: 'main/products?sortBy=loanId&sortDesc=true&size=20&states=BEFORE_OPEN,OPENING',
  desc: '가장 중요! 상품목록',
  data: {
    total: 1,
    content: [
      {
        id: 583,
        title: '제1725호',
        code: 'P247000499',
        type: 'STOCK_PURCHASE',
        defaultFile:
          'https://kr.object.fin-ncloudstorage.com/lending/test/PRODUCT_DEFAULT_P247000499.jpg',
        memberCode: 'M330000011',
        state: 'OPENING',
        step: 0,
        total: 0,
        approvalState: 'APPROVAL',
        currentAmount: 100000,
        totalAmount: 1000000,
        totalCount: 10,
        executeAmount: 0,
        remainAmount: 0,
        averageAmount: 0,
        feeRate: 0.0,
        investorProfit: 12.0,
        repayPeriod: 1,
        repayPeriodType: 'MONTH',
        platformFeeInvestor: 1.0,
        openAt: '2025-08-26 16:15:00',
        startAt: '2025-08-26 16:16:00',
        endAt: '2025-08-29 17:15:59',
        launchAt: '2025-08-26 16:46:00',
        expiredAt: null,
        createdAt: '2025-08-26 16:14:23',
        loanDateAt: '2025-08-26 16:14:02',
        loaner: null,
        groupId: 158,
        groupType: '집중형',
        managerCode: null,
        managerName: null,
        suggesterCode: null,
        suggesterName: null,
        tradingCompany: 'NH투자증권',
        tradingCompanyCode: null,
        lossCutRate: 125,
        withdrawalRate: null,
        rmsAccountEvaluateAmount: 150000000,
        riskScore: 0,
        kcreditOverdueReported: 'N',
      },
    ],
    details: {
      isLast: true,
      offset: 0,
      previous: 1,
      hasPrevious: false,
      next: 1,
      hasNext: false,
      totalPages: 1,
      totalCount: 1,
    },
  },
} as const;

export const getAcquisition = {
  uri: 'acquisition/list/6',
  desc: '하이마켓 양수(넘겨받기) 리스트',
  data: [
    {
      id: 102,
      productTitle: '제836호',
      productGroupType: '집중형',
      remainPrincipal: '110000',
      remainPaymentDays: '-610',
      tradingCompany: '신한은행',
      state: 'COMPLETE',
      investorProfit: '11',
    },
    {
      id: 98,
      productTitle: '제831호',
      productGroupType: '집중형',
      remainPrincipal: '4900000',
      remainPaymentDays: '-611',
      tradingCompany: 'NH투자증권',
      state: 'COMPLETE',
      investorProfit: '11',
    },
  ],
} as const;

export const almInfo = {
  uri: 'aml/M330000017/info',
  desc: '자금세탁방지 관련 정보',
  data: {
    isRedo: false,
    amlIndividual: null,
    amlCorporation: null,
    amlIndividualAttorney: null,
  },
};
