// obj architecture
/* 
{
    "code": 1000,
    "message": "SUCCESS",
    "payload": {...}
}
*/

export const member = {
  uri: '/members/member',
  desc: '유저 정보',
  id: 63,
  code: 'M330000017',
  purpose: 'INVEST',
  authorities: ['ROLE_MEMBER'],
  investorTypeCode: 'I320',
  investorTypeName: 'CREDIT_FINANCIAL_INSTITUTION',
  loanerTypeCode: 'B300',
  loanerTypeName: 'CORPORATION_LOANER',
  email: 'hana@hanabank.co.kr',
  englishName: 'HANABANK',
  isPasswordChangeRequest: false,
  name: '하나은행',
  jobName: '',
  guid: 'LTEyMjMzOTE0NDA',
  sex: 'MQALE',
  type: 'CORPORATION',
  state: 'ACTIVE',
  amlState: 'AML_DONE',
  mainAddress: '서울 강서구 월정로18길 9 (화곡동)',
  subAddress: '3 층',
  sourceOfFund: '',
  specialIndustry: '',
  phone: '01064562278',
  contactPhone: '',
  encParam: null,
  amlId: null,
  pinId: null,
  socialCode1: '123456',
  socialCode2: '8121212',
  lastLoginAt: '2025-08-27 15:17:44',
  memo: null,
  isMailNotify: false,
  isSmsNotify: false,
  isKakaoNotify: false,
  telephone: '0212344321',
  businessCode: '1101122022',
  businessName: '이상욱',
  businessEnglishName: 'PARKJUNSEONG',
  corporateCode: '2222223******',
  ceoName: '박준성',
  ceoEnglishName: 'lee sy',
  ceoSocialCode1: '501212',
  ceoSocialCode2: '1234567',
  ownerName: '이승열',
  ownerEnglishName: 'lee sy',
  ownerSocialCode1: '501212',
  ownerSocialCode2: '501212',
  depositAccountTid: 'TTTTTT',
  depositAccountBank: 'NH농협은행',
  depositAccountCode: '011',
  depositAccountNumber: '79018940093715',
  depositAccountOwner: '하나은행',
  depositAccountCreatedAt: '2023-04-14 09:35:32',
  balance: 9891400,
  accountState: 'EXIST_SUCCESS',
  accountEnhancedState: 'NONE',
  kycState: 'SUCCESS',
  withdrawAccountBank: '국민은행',
  withdrawAccountCode: '004',
  withdrawAccountNumber: '778210218961',
  withdrawAccountOwner: '하나은행',
  withdrawAccountAddedAt: null,
  withdrawAccountExistAt: '2024-09-03 09:46:40',
  withdrawAccountValidAt: null,
  withdrawAccountValidIng: false,
  withdrawAccountValidLog: '',
  withdrawAccountEnhanceLog: '',
  kycLog: '',
  certLog: '',
  withdrawAccountValidTimeout: false,
  withdrawAccountEnhanceAt: null,
  repayAccountTid: null,
  repayAccountBank: null,
  repayAccountCode: null,
  repayAccountNumber: null,
  repayAccountOwner: null,
  repayAccountCreatedAt: null,
  certAt: null,
  isLoaning: false,
  isBelongCompany: false,
  loginFailCount: 0,
  createdAt: '2023-02-23 10:54:15',
  updatedAt: '2025-08-27 15:17:44',
  deletedAt: null,
  emailAuthCode: '',
  emailAuthCodeAt: null,
  emailAuthAt: null,
  cddAt: '2026-09-08 00:10:00',
  eddAt: null,
  riskScore: null,
  incomeScore: null,
  investorExpDate: null,
  ceoCorporateCode: null,
  ownerCorporateCode: null,
  leaveReason: null,
  isLeave: false,
  postCode: '07775',
  suggesterCode: null,
  suggesterName: null,
  managerCode: null,
  managerName: null,
  sourceOfFunds: null,
  sourceOfFundsEtc: null,
  purposeOfInvest: null,
  purposeOfInvestEtc: null,
  passwordDate: '2025-07-01 12:17:48',
  isDormant: false,
  meRecommenderCode: '3ABA',
  recommenderCode: null,
  nameOfAttorney: null,
  englishNameOfAttorney: null,
  socialCodeOfAttorney1: null,
  socialCodeOfAttorney2: null,
  memberCodeAmlAttornery: null,
  isMinor: false,
  level: 'NORMAL',
  mgLevelStartDate: null,
  mgLevelEndDate: null,
  mgmPoint: 0,
  multipleInvestRenewal: false,
} as const;

export const mainData = {
  desc: '메인화면 표시용 데이터 전부',
  uri: '/main/banners/MAIN',
  id: 53,
  type: 'MAIN',
  title: '하이펀딩, 온라인투자연계금융업 대출잔고 1위 달성',
  mobileTitle: null,
  titleColor: '#ffffffff',
  titlePcFontSize: 30,
  titleMoFontSize: 15,
  description: '',
  mobileDescription: null,
  descriptionColor: '#ffffffff',
  descPcFontSize: 20,
  descMoFontSize: 10,
  subDescription: '[관련 뉴스기사 보러가기]',
  mobileSubDescription: null,
  subDescriptionColor: '#ffffffff',
  subDescPcFontSize: 18,
  subDescMoFontSize: 12,
  file1:
    'https://kr.object.fin-ncloudstorage.com/lending/test/5a19a6d7-092b-4fea-a6e5-41a57f584e7c',
  file2:
    'https://kr.object.fin-ncloudstorage.com/lending/test/8d5e247f-5b9b-4ba5-a8a5-27247c4146b6',
  link: 'https://www.sedaily.com/NewsView/2GV6ZTH8XC',
  linkColor: '#ffffffff',
  state: 'ACTIVE',
  isNewTab: true,
  titleBold: true,
  descriptionBold: true,
  subDescriptionBold: true,
  titlePcTop: 160,
  titleMobileTop: 128,
  startAt: '2025-07-02 17:19:47',
  endAt: '2027-07-03 23:59:44',
  createdAt: '2025-07-02 16:59:11',
  updatedAt: '2025-07-03 09:08:09',
} as const;
